import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateUsuariosAndAuditoria1757398765705 implements MigrationInterface {
    name = 'CreateUsuariosAndAuditoria1757398765705'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "horarios_atendimento" DROP CONSTRAINT "FK_HORARIO_ATENDIMENTO_UNIDADE"`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" DROP CONSTRAINT "FK_DADO_BANCARIO_UNIDADE"`);
        await queryRunner.query(`ALTER TABLE "cnae_secundarios" DROP CONSTRAINT "FK_CNAE_SECUNDARIO_UNIDADE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_UNIDADE_SAUDE_CNPJ"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_UNIDADE_SAUDE_CIDADE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_UNIDADE_SAUDE_ATIVO"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PACIENTE_CPF_EMPRESA"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PACIENTE_NOME"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PACIENTE_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PACIENTE_EMPRESA"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PACIENTE_EMAIL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PACIENTE_CONVENIO"`);
        await queryRunner.query(`CREATE TABLE "modulos_sistema" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying(50) NOT NULL, "nome" character varying(100) NOT NULL, "ordem" integer, "ativo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_5c3bbf0478d5f0f852f953f14e4" UNIQUE ("codigo"), CONSTRAINT "PK_bed8a40a6f972f73dfd174ec3b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipos_permissao" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying(50) NOT NULL, "nome" character varying(100) NOT NULL, "descricao" text, "ativo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8a0a1450b7faf6983759fd27f70" UNIQUE ("codigo"), CONSTRAINT "PK_346a21e211df078f183e2d322bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuarios_permissoes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid NOT NULL, "modulo_id" uuid NOT NULL, "permissao_id" uuid NOT NULL, "unidade_saude_id" uuid, "concedido" boolean NOT NULL DEFAULT false, "horario_inicio" TIME, "horario_fim" TIME, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_63b32d07380829540b618f91de1" UNIQUE ("usuario_id", "modulo_id", "permissao_id", "unidade_saude_id"), CONSTRAINT "PK_299782b732019776fa033122cce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo_interno" character varying(50), "nome_completo" character varying(255) NOT NULL, "cpf" character varying(11), "telefone" character varying(20), "celular_whatsapp" character varying(20), "cargo_funcao" character varying(100), "cnpj_associado" character varying(14), "dados_admissao" character varying(255), "foto_url" character varying(500), "email" character varying(255) NOT NULL, "senha_hash" character varying(255) NOT NULL, "resetar_senha" boolean NOT NULL DEFAULT false, "validacao_2_etapas" boolean NOT NULL DEFAULT false, "metodo_validacao" character varying(50), "pergunta_recuperacao" character varying(255), "resposta_recuperacao_hash" character varying(255), "tentativas_login_falhas" integer NOT NULL DEFAULT '0', "bloqueado_ate" TIMESTAMP, "ultimo_login" TIMESTAMP, "ativo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ebebcaef8457dcff6e6d69f17b0" UNIQUE ("cpf"), CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5" UNIQUE ("email"), CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuarios_unidades" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid NOT NULL, "unidade_saude_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_aebf2cd860dcbf1bb56d1cc7839" UNIQUE ("usuario_id", "unidade_saude_id"), CONSTRAINT "PK_117e468a0c5e8c84c52425d9b55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."logs_auditoria_modulo_enum" AS ENUM('auth', 'atendimento', 'exames', 'financeiro', 'crm', 'auditoria', 'estoque', 'tiss', 'tarefas', 'bi', 'portal_cliente', 'portal_medico', 'integracoes', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."logs_auditoria_tipo_operacao_enum" AS ENUM('CREATE', 'UPDATE', 'DELETE', 'SELECT', 'LOGIN', 'LOGOUT', 'EXPORT', 'IMPORT', 'APPROVE', 'REJECT', 'SIGN')`);
        await queryRunner.query(`CREATE TABLE "logs_auditoria" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid, "modulo" "public"."logs_auditoria_modulo_enum" NOT NULL, "tabela" character varying(100) NOT NULL, "registro_id" character varying, "tipo_operacao" "public"."logs_auditoria_tipo_operacao_enum" NOT NULL, "valores_anteriores" json, "valores_novos" json, "valores_alterados" json, "ip_address" character varying(45) NOT NULL, "user_agent" character varying(500), "endpoint" character varying(500), "metodo_http" character varying(10), "status_http" integer, "tempo_execucao_ms" integer, "observacoes" character varying(1000), "metadados_adicionais" json, "sessao_id" character varying(100), "operacao_sensivel" boolean NOT NULL DEFAULT false, "falha_operacao" boolean NOT NULL DEFAULT false, "erro_detalhes" character varying(500), "criado_em" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_034892b883599b2857c75d5d639" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fda50a5e41d657e124267ff029" ON "logs_auditoria" ("tipo_operacao", "criado_em") `);
        await queryRunner.query(`CREATE INDEX "IDX_8de5b4cb89974b76e6c2249fdb" ON "logs_auditoria" ("usuario_id", "criado_em") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4201027019a889394112ec5eb" ON "logs_auditoria" ("modulo", "tabela", "criado_em") `);
        await queryRunner.query(`CREATE TABLE "historico_alteracoes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid, "tabela_origem" character varying(100) NOT NULL, "registro_id" character varying NOT NULL, "campo_alterado" character varying(100) NOT NULL, "valor_anterior" text, "valor_novo" text, "tipo_campo" character varying(50) NOT NULL, "motivo_alteracao" character varying(500), "ip_address" character varying(45) NOT NULL, "user_agent" character varying(500), "alteracao_critica" boolean NOT NULL DEFAULT false, "requer_aprovacao" boolean NOT NULL DEFAULT false, "aprovada" boolean NOT NULL DEFAULT false, "aprovada_por" uuid, "aprovada_em" TIMESTAMP, "contexto_adicional" json, "criado_em" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_245e326ab6b7fb61acb63cf4919" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_61be1adbef88e5107f4785377a" ON "historico_alteracoes" ("usuario_id", "criado_em") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c330e5d091d4d176bd0f1ed5b" ON "historico_alteracoes" ("tabela_origem", "registro_id", "criado_em") `);
        await queryRunner.query(`CREATE TYPE "public"."auditoria_logs_tipo_log_enum" AS ENUM('ACESSO', 'ALTERACAO', 'ERRO', 'ACAO')`);
        await queryRunner.query(`CREATE TYPE "public"."auditoria_logs_operacao_enum" AS ENUM('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'LOGIN_FALHA')`);
        await queryRunner.query(`CREATE TYPE "public"."auditoria_logs_nivel_enum" AS ENUM('INFO', 'WARNING', 'ERROR', 'CRITICAL')`);
        await queryRunner.query(`CREATE TABLE "auditoria_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_log" "public"."auditoria_logs_tipo_log_enum" NOT NULL, "usuario_id" uuid NOT NULL, "data_hora" TIMESTAMP NOT NULL, "ip_address" character varying(45), "user_agent" text, "unidade_saude_id" uuid, "modulo" character varying(100), "acao" character varying(100), "entidade" character varying(100), "entidade_id" uuid, "operacao" "public"."auditoria_logs_operacao_enum", "usuario_alterou_id" uuid, "dados_alteracao" jsonb, "detalhes" text, "nivel" "public"."auditoria_logs_nivel_enum" NOT NULL DEFAULT 'INFO', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a34200533b6e7b5be027e7ea494" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66fc176e8f39ce47ed8e711dd6" ON "auditoria_logs" ("entidade", "entidade_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4ab436910a0a64d3163470c58" ON "auditoria_logs" ("data_hora") `);
        await queryRunner.query(`CREATE INDEX "IDX_f109ccd0dc4c2958aad2523d7c" ON "auditoria_logs" ("usuario_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd57b88345f49a1052ff6ff9ce" ON "auditoria_logs" ("tipo_log") `);
        await queryRunner.query(`ALTER TABLE "horarios_atendimento" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "horarios_atendimento" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ALTER COLUMN "codigo_banco" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" DROP COLUMN "digito_agencia"`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ADD "digito_agencia" character varying(2)`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" DROP COLUMN "digito_conta"`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ADD "digito_conta" character varying(2)`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ALTER COLUMN "tipo_conta" SET DEFAULT 'CORRENTE'`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cnae_secundarios" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cnae_secundarios" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "unidades_saude" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "unidades_saude" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."codigo_interno" IS 'Código interno do paciente (ex: PAC123123)'`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP CONSTRAINT "UQ_22567ede4e0c8493bc2ca03354f"`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."nome" IS 'Nome completo do paciente'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."nome_social" IS 'Nome social do paciente'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."usar_nome_social" IS 'Se deve usar o nome social'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."sexo" IS 'M - Masculino, F - Feminino, O - Outro'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."data_nascimento" IS 'Data de nascimento'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."nome_mae" IS 'Nome da mãe'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."prontuario" IS 'Número do prontuário'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."rg" IS 'RG do paciente'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."cpf" IS 'CPF sem formatação'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."estado_civil" IS 'Estado civil'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."email" IS 'E-mail do paciente'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."contatos" IS 'Contatos (telefone/celular principal)'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."whatsapp" IS 'WhatsApp'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."profissao" IS 'Profissão'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."observacao" IS 'Observações gerais sobre o paciente'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."convenio_id" IS 'ID do convênio'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."plano" IS 'Nome do plano'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."validade" IS 'Validade do convênio'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."matricula" IS 'Matrícula do convênio'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."nome_titular" IS 'Nome do titular do convênio'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."cartao_sus" IS 'Cartão SUS'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."cep" IS 'CEP sem formatação'`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "rua" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."rua" IS 'Rua/Logradouro'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."numero" IS 'Número do endereço'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."bairro" IS 'Bairro'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."complemento" IS 'Complemento do endereço'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."cidade" IS 'Cidade'`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "estado" character(2) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."estado" IS 'Estado (UF)'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."foto_url" IS 'URL da foto do paciente'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."status" IS 'Status do paciente no sistema'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."empresa_id" IS 'ID da empresa (CNPJ/Filial)'`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."criado_em" IS 'Data de criação do registro'`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "criado_em" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."atualizado_em" IS 'Data da última atualização'`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "atualizado_em" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "criado_por" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."criado_por" IS 'ID do usuário que criou o registro'`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "atualizado_por" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."atualizado_por" IS 'ID do usuário que atualizou o registro'`);
        await queryRunner.query(`CREATE INDEX "IDX_3e42aa57b367579102b47df907" ON "pacientes" ("nome") `);
        await queryRunner.query(`CREATE INDEX "IDX_29ba82a65e54af32516da4ba46" ON "pacientes" ("contatos") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b1d1c80bdf7c29c7187ef8939" ON "pacientes" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_87912d0aec876ebe8d448c8bd4" ON "pacientes" ("cpf", "empresa_id") `);
        await queryRunner.query(`ALTER TABLE "horarios_atendimento" ADD CONSTRAINT "FK_b8f48b102e65e65e024ef042dcb" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ADD CONSTRAINT "FK_7cd2d7d4e44969cc30e82a3ae94" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cnae_secundarios" ADD CONSTRAINT "FK_f1727763ae5e376914bbf83c36f" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_permissoes" ADD CONSTRAINT "FK_a590446adec482807e08a9f17fc" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_permissoes" ADD CONSTRAINT "FK_0a74ea10224f6e762e8caa51a86" FOREIGN KEY ("modulo_id") REFERENCES "modulos_sistema"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_permissoes" ADD CONSTRAINT "FK_bc6db171d9b3fa0891abc5c204c" FOREIGN KEY ("permissao_id") REFERENCES "tipos_permissao"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_permissoes" ADD CONSTRAINT "FK_4a8a6519436bb8122b64ddf4646" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_unidades" ADD CONSTRAINT "FK_67de55d1de2d34ca62b69987bc9" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_unidades" ADD CONSTRAINT "FK_4dc30869c01c4519a07f785bae5" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logs_auditoria" ADD CONSTRAINT "FK_40a1967a69863f775a46300313b" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historico_alteracoes" ADD CONSTRAINT "FK_3a912411aaff60fa16bb48d283e" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historico_alteracoes" ADD CONSTRAINT "FK_8c19140052e9e09b159e71e29f2" FOREIGN KEY ("aprovada_por") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auditoria_logs" ADD CONSTRAINT "FK_f109ccd0dc4c2958aad2523d7c9" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auditoria_logs" ADD CONSTRAINT "FK_cc91fa69a0d88e4d06dd0e8ef12" FOREIGN KEY ("usuario_alterou_id") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auditoria_logs" ADD CONSTRAINT "FK_fd6e49687c6e8f6729c2eda6608" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auditoria_logs" DROP CONSTRAINT "FK_fd6e49687c6e8f6729c2eda6608"`);
        await queryRunner.query(`ALTER TABLE "auditoria_logs" DROP CONSTRAINT "FK_cc91fa69a0d88e4d06dd0e8ef12"`);
        await queryRunner.query(`ALTER TABLE "auditoria_logs" DROP CONSTRAINT "FK_f109ccd0dc4c2958aad2523d7c9"`);
        await queryRunner.query(`ALTER TABLE "historico_alteracoes" DROP CONSTRAINT "FK_8c19140052e9e09b159e71e29f2"`);
        await queryRunner.query(`ALTER TABLE "historico_alteracoes" DROP CONSTRAINT "FK_3a912411aaff60fa16bb48d283e"`);
        await queryRunner.query(`ALTER TABLE "logs_auditoria" DROP CONSTRAINT "FK_40a1967a69863f775a46300313b"`);
        await queryRunner.query(`ALTER TABLE "usuarios_unidades" DROP CONSTRAINT "FK_4dc30869c01c4519a07f785bae5"`);
        await queryRunner.query(`ALTER TABLE "usuarios_unidades" DROP CONSTRAINT "FK_67de55d1de2d34ca62b69987bc9"`);
        await queryRunner.query(`ALTER TABLE "usuarios_permissoes" DROP CONSTRAINT "FK_4a8a6519436bb8122b64ddf4646"`);
        await queryRunner.query(`ALTER TABLE "usuarios_permissoes" DROP CONSTRAINT "FK_bc6db171d9b3fa0891abc5c204c"`);
        await queryRunner.query(`ALTER TABLE "usuarios_permissoes" DROP CONSTRAINT "FK_0a74ea10224f6e762e8caa51a86"`);
        await queryRunner.query(`ALTER TABLE "usuarios_permissoes" DROP CONSTRAINT "FK_a590446adec482807e08a9f17fc"`);
        await queryRunner.query(`ALTER TABLE "cnae_secundarios" DROP CONSTRAINT "FK_f1727763ae5e376914bbf83c36f"`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" DROP CONSTRAINT "FK_7cd2d7d4e44969cc30e82a3ae94"`);
        await queryRunner.query(`ALTER TABLE "horarios_atendimento" DROP CONSTRAINT "FK_b8f48b102e65e65e024ef042dcb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87912d0aec876ebe8d448c8bd4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b1d1c80bdf7c29c7187ef8939"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29ba82a65e54af32516da4ba46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e42aa57b367579102b47df907"`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."atualizado_por" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "atualizado_por" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."criado_por" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "criado_por" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "atualizado_em" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."atualizado_em" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "criado_em" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."criado_em" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."empresa_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."foto_url" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."estado" IS 'Estado (UF)'`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "estado" character varying(2) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."cidade" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."complemento" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."bairro" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."numero" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."rua" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ALTER COLUMN "rua" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."cep" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."cartao_sus" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."nome_titular" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."matricula" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."validade" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."plano" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."convenio_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."observacao" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."profissao" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."whatsapp" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."contatos" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."email" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."estado_civil" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."cpf" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."rg" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."prontuario" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."nome_mae" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."data_nascimento" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."sexo" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."usar_nome_social" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."nome_social" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."nome" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD CONSTRAINT "UQ_22567ede4e0c8493bc2ca03354f" UNIQUE ("codigo_interno")`);
        await queryRunner.query(`COMMENT ON COLUMN "pacientes"."codigo_interno" IS NULL`);
        await queryRunner.query(`ALTER TABLE "unidades_saude" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "unidades_saude" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cnae_secundarios" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cnae_secundarios" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ALTER COLUMN "tipo_conta" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" DROP COLUMN "digito_conta"`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ADD "digito_conta" character varying(5)`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" DROP COLUMN "digito_agencia"`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ADD "digito_agencia" character varying(5)`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ALTER COLUMN "codigo_banco" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "horarios_atendimento" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "horarios_atendimento" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd57b88345f49a1052ff6ff9ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f109ccd0dc4c2958aad2523d7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4ab436910a0a64d3163470c58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66fc176e8f39ce47ed8e711dd6"`);
        await queryRunner.query(`DROP TABLE "auditoria_logs"`);
        await queryRunner.query(`DROP TYPE "public"."auditoria_logs_nivel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."auditoria_logs_operacao_enum"`);
        await queryRunner.query(`DROP TYPE "public"."auditoria_logs_tipo_log_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c330e5d091d4d176bd0f1ed5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61be1adbef88e5107f4785377a"`);
        await queryRunner.query(`DROP TABLE "historico_alteracoes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4201027019a889394112ec5eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8de5b4cb89974b76e6c2249fdb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fda50a5e41d657e124267ff029"`);
        await queryRunner.query(`DROP TABLE "logs_auditoria"`);
        await queryRunner.query(`DROP TYPE "public"."logs_auditoria_tipo_operacao_enum"`);
        await queryRunner.query(`DROP TYPE "public"."logs_auditoria_modulo_enum"`);
        await queryRunner.query(`DROP TABLE "usuarios_unidades"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "usuarios_permissoes"`);
        await queryRunner.query(`DROP TABLE "tipos_permissao"`);
        await queryRunner.query(`DROP TABLE "modulos_sistema"`);
        await queryRunner.query(`CREATE INDEX "IDX_PACIENTE_CONVENIO" ON "pacientes" ("convenio_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_PACIENTE_EMAIL" ON "pacientes" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_PACIENTE_EMPRESA" ON "pacientes" ("empresa_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_PACIENTE_STATUS" ON "pacientes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_PACIENTE_NOME" ON "pacientes" ("nome") `);
        await queryRunner.query(`CREATE INDEX "IDX_PACIENTE_CPF_EMPRESA" ON "pacientes" ("cpf", "empresa_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_UNIDADE_SAUDE_ATIVO" ON "unidades_saude" ("ativo") `);
        await queryRunner.query(`CREATE INDEX "IDX_UNIDADE_SAUDE_CIDADE" ON "unidades_saude" ("cidade") `);
        await queryRunner.query(`CREATE INDEX "IDX_UNIDADE_SAUDE_CNPJ" ON "unidades_saude" ("cnpj") `);
        await queryRunner.query(`ALTER TABLE "cnae_secundarios" ADD CONSTRAINT "FK_CNAE_SECUNDARIO_UNIDADE" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dados_bancarios" ADD CONSTRAINT "FK_DADO_BANCARIO_UNIDADE" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "horarios_atendimento" ADD CONSTRAINT "FK_HORARIO_ATENDIMENTO_UNIDADE" FOREIGN KEY ("unidade_saude_id") REFERENCES "unidades_saude"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
