export enum TipoEmpresaEnum {
  CONVENIOS = 'CONVENIOS',
  LABORATORIO_APOIO = 'LABORATORIO_APOIO',
  TELEMEDICINA = 'TELEMEDICINA',
  FORNECEDORES = 'FORNECEDORES',
  PRESTADORES_SERVICOS = 'PRESTADORES_SERVICOS',
}

export enum TipoImposto {
  IRRF = 'IRRF',
  PIS = 'PIS',
  COFINS = 'COFINS',
  CSLL = 'CSLL',
  ISS = 'ISS',
  IBS = 'IBS',
  CBS = 'CBS',
}

export enum FormaPagamentoEnum {
  BOLETO = 'BOLETO',
  PIX = 'PIX',
  CARTAO_CREDITO = 'CARTAO_CREDITO',
  CARTAO_DEBITO = 'CARTAO_DEBITO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  DINHEIRO = 'DINHEIRO',
  CHEQUE = 'CHEQUE',
}
